name: Release Asset
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: C:\Users\Amits\Desktop\Android-Debloater-\platform-tools\New Text Document.txt  # Yahan apni file ka path aur naam dein
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}